VERSION_SUFFIX = "a0"
VERSION_PATCH  = "0" + (VERSION_SUFFIX or "")
VERSION_MINOR  = "0"
VERSION_MAJOR  = "1"

VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)
VERSION = ".".join([str(x) for x in VERSION_INFO])
